[template.environment]
  GQL_HOST = "WordPress URL https://cinavape.com"
  NUXT_IMAGE_DOMAINS = "Comma separated list of domains. cinavape.com"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://cinavape.com/.*"]
